CFLAGS = -std=c11 -Wall -Wextra -Wstrict-prototypes -Wredundant-decls -Wshadow -pedantic -pedantic -fno-strict-aliasing -D_XOPEN_SOURCE=700 -O2 -I./
LDFLAGS = 
OPENACC_FLAGS = -fopenacc -foffload=nvptx-none -foffload="-O3" 
BIN = pi

all: $(BIN)
	
pi: pi.c
	$(CC) $(CFLAGS) -o $@ $? $(LDFLAGS) $(OPENACC_FLAGS)

clean:
	rm -f $(BIN)
	rm -f *.o 

